### ISSUE TITLE
Git installed but can't run

### ISSUE THREAD

**Issue by cody151** [effusiveperiscope/so-vits-svc#13]
OSError: Looks like you do not have git installed, please install.

Platform Win x64
Python 3.9.2
Running the inference notebook locally

Hello I am trying to run this locally on my machine but for the setup HF step it keeps saying git is missing despite me installing GitHub 64bit as well as GitHub via pip.

Any ideas?

**Comment by effusiveperiscope** [comment]
Git is not the same as github. Please install git from https://git-scm.com/ and try again

**Comment by effusiveperiscope** [comment]
Also on Windows I would recommend you try one of the release zips for a simpler setup https://github.com/effusiveperiscope/so-vits-svc/tags

**Comment by cody151** [comment]
> Also on Windows I would recommend you try one of the release zips for a simpler setup https://github.com/effusiveperiscope/so-vits-svc/tags

Thank you I will try installing git scm soon, I was going to use the installable version but the features are lacking compared to the notebook version and I think it's a few iterations behind also

**Comment by effusiveperiscope** [comment]
How is the installable version lacking compared to the notebook version?

**Comment by cody151** [comment]
> How is the installable version lacking compared to the notebook version?

no rubberband, no pygame, no crepe

I think the installable is also v0.1 which is quite a gap to v0.2

**Comment by cody151** [comment]
> Git is not the same as github. Please install git from https://git-scm.com/ and try again

I've installed git scm but still getting:

FileNotFoundError                         Traceback (most recent call last)
File C:\Python\Python392\lib\site-packages\huggingface_hub\repository.py:569, in Repository.check_git_versions(self)
    568 try:
--> 569     git_version = run_subprocess("git --version", self.local_dir).stdout.strip()
    570 except FileNotFoundError:


I did install the latest version 64bit

**Comment by effusiveperiscope** [comment]
> > How is the installable version lacking compared to the notebook version?
> 
> no rubberband, no pygame, no crepe
> 
> I think the installable is also v0.1 which is quite a gap to v0.2

The installable has a 0.2 version. Internally it git pulls this repository so it should be pulling the same code that the notebook pulls. Rubberband, pygame, and crepe all provide optional features for the GUI that are also not present in the notebook version.

What are you using to run the notebook locally? Is git on your PATH? Is there any error output after what you posted?

**Comment by cody151** [comment]
> > > How is the installable version lacking compared to the notebook version?
> 
> > 
> 
> > no rubberband, no pygame, no crepe
> 
> > 
> 
> > I think the installable is also v0.1 which is quite a gap to v0.2
> 
> 
> 
> The installable has a 0.2 version. Internally it git pulls this repository so it should be pulling the same code that the notebook pulls. Rubberband, pygame, and crepe all provide optional features for the GUI that are also not present in the notebook version.
> 
> 
> 
> What are you using to run the notebook locally? Is git on your PATH? Is there any error output after what you posted?

IDE: VSCode Win10 64bit
I may try the installer version then as well, regarding the notebook version I'm still getting the same error (same output) git not found despite adding C:/program files(x86)/git and ../git/cmd to windows system environmental variables PATH entry.

Any ideas?

**Comment by cody151** [comment]
Do you know what exactly is supposed to be added to the PATH to get git scm working, maybe a git executable or is it a specific directory?

**Comment by effusiveperiscope** [comment]
The git executable should be inside Program Files/git/bin. If you can't run the git.exe from inside your terminal then it's not on your PATH (you have to restart the terminal after changes to PATH though).

**Comment by cody151** [comment]
> The git executable should be inside Program Files/git/bin. If you can't run the git.exe from inside your terminal then it's not on your PATH (you have to restart the terminal after changes to PATH though).

Fixed it thanks!!!
