### ISSUE TITLE
Installable version not working

### ISSUE THREAD

**Issue by cody151** [effusiveperiscope/so-vits-svc#14]
Setup batch file was run and completed, the cmd prompt stated to open run batch file and opening the run batch just hangs on an empty blank cmd screen and nothing runs. CUDA already installed to latest version.

Win10 64bit
Python3.9

**Comment by cody151** [comment]
Edit: this error message displays

DEBUG:matplotlib:matplotlib data path: E:\aivocals\install\miniconda\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\jj\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
DEBUG:matplotlib:CACHEDIR=C:\Users\jj\.matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from C:\Users\jj\.matplotlib\fontlist-v330.json
Note: Automatic mode not available.To enable: pip install pygame keyboard
INFO: Could not find files for the given pattern(s).
Note: Rubberband is not available. Timestretch not available.
Could not find TalkNet on address 127.0.0.1:8050
Traceback (most recent call last):
  File "inference_gui2.py", line 1185, in <module>
    w = InferenceGui2()
  File "inference_gui2.py", line 701, in __init__
    self.audio_recorder = AudioRecorder(self)
  File "inference_gui2.py", line 370, in __init__
    self.record_shortcut = QShortcut(QKeySequence(RECORD_SHORTCUT), self)
NameError: name 'RECORD_SHORTCUT' is not defined
Press any key to continue . . .

**Comment by effusiveperiscope** [comment]
Sorry; please update/pull and try again. Might be fixed by 24237af but cannot test on Windows right now.

**Comment by cody151** [comment]
> Sorry; please update/pull and try again. Might be fixed by 24237af but cannot test on Windows right now.

Fixed it thanks
