### ISSUE TITLE
Numpy deprecated error in local copy?

### ISSUE THREAD

**Issue by mya2152** [effusiveperiscope/so-vits-svc#15]
Win10 x64
48GB RAM
VSCode Python 3.9.2
NVIDIA M1000M CUDA toolkit installed latest version (initial GPU step didn't show any errors)

All steps completed fine but right at final file conversion step when pressing the convert button, this error appears:

**### Error:**
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?8807c296-b8c1-4a64-9ff6-58536e29aa10)---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 80, in InferenceGui.__init__..convert_cb(btn)
     79 def convert_cb(btn):
---> 80   self.convert()

Cell In[1], line 112, in InferenceGui.convert(self)
    109 print(spkpth2)
    110 print(os.path.exists(spkpth2))
--> 112 svc_model = Svc(speaker["model_path"], speaker["cfg_path"], 
    113   cluster_model_path=speaker["cluster_path"])
    115 input_filepaths = [f for f in glob.glob('/content/**/*.*', recursive=True)
    116  if f not in existing_files and 
    117  any(f.endswith(ex) for ex in ['.wav','.flac','.mp3','.ogg','.opus'])]
    118 for name in input_filepaths:

File [E:\aivocals\bin\so-vits-svc-eff-4.0\inference\infer_tool.py:128](file:///E:/aivocals/bin/so-vits-svc-eff-4.0/inference/infer_tool.py:128), in Svc.__init__(self, net_g_path, config_path, device, cluster_model_path)
    125 self.f0_cache = {}
    127 # 加载hubert
--> 128 self.hubert_model = sovits_utils.get_hubert_model().to(self.dev)
    129 self.load_model()
    130 if os.path.exists(cluster_model_path):

File [E:\aivocals\bin\so-vits-svc-eff-4.0\sovits_utils.py:236](file:///E:/aivocals/bin/so-vits-svc-eff-4.0/sovits_utils.py:236), in get_hubert_model()
    234 vec_path = "hubert/checkpoint_best_legacy_500.pt"
...

AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**### // End of output**

Any ideas ?

**Comment by effusiveperiscope** [comment]
Do you have a full traceback that shows which library/code the numpy error came from?

**Comment by mya2152** [comment]
> Do you have a full traceback that shows which library/code the numpy error came from?

Please see below:

{
	"name": "AttributeError",
	"message": "module 'numpy' has no attribute 'object'.\n`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \nThe aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations",
	"stack": "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)\nCell \u001b[1;32mIn[1], line 80\u001b[0m, in \u001b[0;36mInferenceGui.__init__.<locals>.convert_cb\u001b[1;34m(btn)\u001b[0m\n\u001b[0;32m     79\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconvert_cb\u001b[39m(btn):\n\u001b[1;32m---> 80\u001b[0m   \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconvert()\n\nCell \u001b[1;32mIn[1], line 112\u001b[0m, in \u001b[0;36mInferenceGui.convert\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    109\u001b[0m \u001b[39mprint\u001b[39m(spkpth2)\n\u001b[0;32m    110\u001b[0m \u001b[39mprint\u001b[39m(os\u001b[39m.\u001b[39mpath\u001b[39m.\u001b[39mexists(spkpth2))\n\u001b[1;32m--> 112\u001b[0m svc_model \u001b[39m=\u001b[39m Svc(speaker[\u001b[39m\"\u001b[39;49m\u001b[39mmodel_path\u001b[39;49m\u001b[39m\"\u001b[39;49m], speaker[\u001b[39m\"\u001b[39;49m\u001b[39mcfg_path\u001b[39;49m\u001b[39m\"\u001b[39;49m], \n\u001b[0;32m    113\u001b[0m   cluster_model_path\u001b[39m=\u001b[39;49mspeaker[\u001b[39m\"\u001b[39;49m\u001b[39mcluster_path\u001b[39;49m\u001b[39m\"\u001b[39;49m])\n\u001b[0;32m    115\u001b[0m input_filepaths \u001b[39m=\u001b[39m [f \u001b[39mfor\u001b[39;00m f \u001b[39min\u001b[39;00m glob\u001b[39m.\u001b[39mglob(\u001b[39m'\u001b[39m\u001b[39m/content/**/*.*\u001b[39m\u001b[39m'\u001b[39m, recursive\u001b[39m=\u001b[39m\u001b[39mTrue\u001b[39;00m)\n\u001b[0;32m    116\u001b[0m  \u001b[39mif\u001b[39;00m f \u001b[39mnot\u001b[39;00m \u001b[39min\u001b[39;00m existing_files \u001b[39mand\u001b[39;00m \n\u001b[0;32m    117\u001b[0m  \u001b[39many\u001b[39m(f\u001b[39m.\u001b[39mendswith(ex) \u001b[39mfor\u001b[39;00m ex \u001b[39min\u001b[39;00m [\u001b[39m'\u001b[39m\u001b[39m.wav\u001b[39m\u001b[39m'\u001b[39m,\u001b[39m'\u001b[39m\u001b[39m.flac\u001b[39m\u001b[39m'\u001b[39m,\u001b[39m'\u001b[39m\u001b[39m.mp3\u001b[39m\u001b[39m'\u001b[39m,\u001b[39m'\u001b[39m\u001b[39m.ogg\u001b[39m\u001b[39m'\u001b[39m,\u001b[39m'\u001b[39m\u001b[39m.opus\u001b[39m\u001b[39m'\u001b[39m])]\n\u001b[0;32m    118\u001b[0m \u001b[39mfor\u001b[39;00m name \u001b[39min\u001b[39;00m input_filepaths:\n\nFile \u001b[1;32mE:\\aivocals\\bin\\so-vits-svc-eff-4.0\\inference\\infer_tool.py:128\u001b[0m, in \u001b[0;36mSvc.__init__\u001b[1;34m(self, net_g_path, config_path, device, cluster_model_path)\u001b[0m\n\u001b[0;32m    125\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mf0_cache \u001b[39m=\u001b[39m {}\n\u001b[0;32m    127\u001b[0m \u001b[39m# 加载hubert\u001b[39;00m\n\u001b[1;32m--> 128\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mhubert_model \u001b[39m=\u001b[39m sovits_utils\u001b[39m.\u001b[39;49mget_hubert_model()\u001b[39m.\u001b[39mto(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdev)\n\u001b[0;32m    129\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mload_model()\n\u001b[0;32m    130\u001b[0m \u001b[39mif\u001b[39;00m os\u001b[39m.\u001b[39mpath\u001b[39m.\u001b[39mexists(cluster_model_path):\n\nFile \u001b[1;32mE:\\aivocals\\bin\\so-vits-svc-eff-4.0\\sovits_utils.py:236\u001b[0m, in \u001b[0;36mget_hubert_model\u001b[1;34m()\u001b[0m\n\u001b[0;32m    234\u001b[0m vec_path \u001b[39m=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39mhubert/checkpoint_best_legacy_500.pt\u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    235\u001b[0m \u001b[39mprint\u001b[39m(\u001b[39m\"\u001b[39m\u001b[39mload model(s) from \u001b[39m\u001b[39m{}\u001b[39;00m\u001b[39m\"\u001b[39m\u001b[39m.\u001b[39mformat(vec_path))\n\u001b[1;32m--> 236\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mfairseq\u001b[39;00m \u001b[39mimport\u001b[39;00m checkpoint_utils\n\u001b[0;32m    237\u001b[0m models, saved_cfg, task \u001b[39m=\u001b[39m checkpoint_utils\u001b[39m.\u001b[39mload_model_ensemble_and_task(\n\u001b[0;32m    238\u001b[0m   [vec_path],\n\u001b[0;32m    239\u001b[0m   suffix\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[0;32m    240\u001b[0m )\n\u001b[0;32m    241\u001b[0m model \u001b[39m=\u001b[39m models[\u001b[39m0\u001b[39m]\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\fairseq\\__init__.py:21\u001b[0m\n\u001b[0;32m     19\u001b[0m \u001b[39m# backwards compatibility to support `from fairseq.X import Y`\u001b[39;00m\n\u001b[0;32m     20\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mfairseq\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mdistributed\u001b[39;00m \u001b[39mimport\u001b[39;00m utils \u001b[39mas\u001b[39;00m distributed_utils\n\u001b[1;32m---> 21\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mfairseq\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mlogging\u001b[39;00m \u001b[39mimport\u001b[39;00m meters, metrics, progress_bar  \u001b[39m# noqa\u001b[39;00m\n\u001b[0;32m     23\u001b[0m sys\u001b[39m.\u001b[39mmodules[\u001b[39m\"\u001b[39m\u001b[39mfairseq.distributed_utils\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m distributed_utils\n\u001b[0;32m     24\u001b[0m sys\u001b[39m.\u001b[39mmodules[\u001b[39m\"\u001b[39m\u001b[39mfairseq.meters\u001b[39m\u001b[39m\"\u001b[39m] \u001b[39m=\u001b[39m meters\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\fairseq\\logging\\progress_bar.py:407\u001b[0m\n\u001b[0;32m    405\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m    406\u001b[0m     _tensorboard_writers \u001b[39m=\u001b[39m {}\n\u001b[1;32m--> 407\u001b[0m     \u001b[39mfrom\u001b[39;00m \u001b[39mtorch\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mutils\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtensorboard\u001b[39;00m \u001b[39mimport\u001b[39;00m SummaryWriter\n\u001b[0;32m    408\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mImportError\u001b[39;00m:\n\u001b[0;32m    409\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\torch\\utils\\tensorboard\\__init__.py:12\u001b[0m\n\u001b[0;32m      9\u001b[0m \u001b[39mdel\u001b[39;00m LooseVersion\n\u001b[0;32m     10\u001b[0m \u001b[39mdel\u001b[39;00m tensorboard\n\u001b[1;32m---> 12\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mwriter\u001b[39;00m \u001b[39mimport\u001b[39;00m FileWriter, SummaryWriter  \u001b[39m# noqa: F401\u001b[39;00m\n\u001b[0;32m     13\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39msummary\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mwriter\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mrecord_writer\u001b[39;00m \u001b[39mimport\u001b[39;00m RecordWriter  \u001b[39m# noqa: F401\u001b[39;00m\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\torch\\utils\\tensorboard\\writer.py:13\u001b[0m\n\u001b[0;32m     11\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcompat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mproto\u001b[39;00m \u001b[39mimport\u001b[39;00m event_pb2\n\u001b[0;32m     12\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mprojector\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mprojector_config_pb2\u001b[39;00m \u001b[39mimport\u001b[39;00m ProjectorConfig\n\u001b[1;32m---> 13\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39msummary\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mwriter\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mevent_file_writer\u001b[39;00m \u001b[39mimport\u001b[39;00m EventFileWriter\n\u001b[0;32m     15\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39m_convert_np\u001b[39;00m \u001b[39mimport\u001b[39;00m make_np\n\u001b[0;32m     16\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39m_embedding\u001b[39;00m \u001b[39mimport\u001b[39;00m (\n\u001b[0;32m     17\u001b[0m     make_mat,\n\u001b[0;32m     18\u001b[0m     make_sprite,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     21\u001b[0m     get_embedding_info,\n\u001b[0;32m     22\u001b[0m )\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\tensorboard\\summary\\__init__.py:25\u001b[0m\n\u001b[0;32m     23\u001b[0m \u001b[39m# If the V1 summary API is accessible, load and re-export it here.\u001b[39;00m\n\u001b[0;32m     24\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m---> 25\u001b[0m     \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39msummary\u001b[39;00m \u001b[39mimport\u001b[39;00m v1  \u001b[39m# noqa: F401\u001b[39;00m\n\u001b[0;32m     26\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mImportError\u001b[39;00m:\n\u001b[0;32m     27\u001b[0m     \u001b[39mpass\u001b[39;00m\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\tensorboard\\summary\\v1.py:26\u001b[0m\n\u001b[0;32m     24\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39maudio\u001b[39;00m \u001b[39mimport\u001b[39;00m summary \u001b[39mas\u001b[39;00m _audio_summary\n\u001b[0;32m     25\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcustom_scalar\u001b[39;00m \u001b[39mimport\u001b[39;00m summary \u001b[39mas\u001b[39;00m _custom_scalar_summary\n\u001b[1;32m---> 26\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhistogram\u001b[39;00m \u001b[39mimport\u001b[39;00m summary \u001b[39mas\u001b[39;00m _histogram_summary\n\u001b[0;32m     27\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mimage\u001b[39;00m \u001b[39mimport\u001b[39;00m summary \u001b[39mas\u001b[39;00m _image_summary\n\u001b[0;32m     28\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mpr_curve\u001b[39;00m \u001b[39mimport\u001b[39;00m summary \u001b[39mas\u001b[39;00m _pr_curve_summary\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\tensorboard\\plugins\\histogram\\summary.py:38\u001b[0m\n\u001b[0;32m     35\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39mnumpy\u001b[39;00m \u001b[39mas\u001b[39;00m \u001b[39mnp\u001b[39;00m\n\u001b[0;32m     37\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhistogram\u001b[39;00m \u001b[39mimport\u001b[39;00m metadata\n\u001b[1;32m---> 38\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhistogram\u001b[39;00m \u001b[39mimport\u001b[39;00m summary_v2\n\u001b[0;32m     41\u001b[0m \u001b[39m# Export V2 versions.\u001b[39;00m\n\u001b[0;32m     42\u001b[0m histogram \u001b[39m=\u001b[39m summary_v2\u001b[39m.\u001b[39mhistogram\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\tensorboard\\plugins\\histogram\\summary_v2.py:38\u001b[0m\n\u001b[0;32m     36\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mplugins\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mhistogram\u001b[39;00m \u001b[39mimport\u001b[39;00m metadata\n\u001b[0;32m     37\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mutil\u001b[39;00m \u001b[39mimport\u001b[39;00m lazy_tensor_creator\n\u001b[1;32m---> 38\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mutil\u001b[39;00m \u001b[39mimport\u001b[39;00m tensor_util\n\u001b[0;32m     41\u001b[0m DEFAULT_BUCKET_COUNT \u001b[39m=\u001b[39m \u001b[39m30\u001b[39m\n\u001b[0;32m     44\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mhistogram\u001b[39m(name, data, step\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, buckets\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, description\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\tensorboard\\util\\tensor_util.py:24\u001b[0m\n\u001b[0;32m     21\u001b[0m \u001b[39mimport\u001b[39;00m \u001b[39msix\u001b[39;00m\n\u001b[0;32m     23\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcompat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mproto\u001b[39;00m \u001b[39mimport\u001b[39;00m tensor_pb2\n\u001b[1;32m---> 24\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcompat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mtensorflow_stub\u001b[39;00m \u001b[39mimport\u001b[39;00m dtypes, compat, tensor_shape\n\u001b[0;32m     27\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mExtractBitsFromFloat16\u001b[39m(x):\n\u001b[0;32m     28\u001b[0m     \u001b[39mreturn\u001b[39;00m np\u001b[39m.\u001b[39masarray(x, dtype\u001b[39m=\u001b[39mnp\u001b[39m.\u001b[39mfloat16)\u001b[39m.\u001b[39mview(np\u001b[39m.\u001b[39muint16)\u001b[39m.\u001b[39mitem()\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\__init__.py:25\u001b[0m\n\u001b[0;32m     23\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcompat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mproto\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mmeta_graph_pb2\u001b[39;00m \u001b[39mimport\u001b[39;00m \u001b[39m*\u001b[39m  \u001b[39m# noqa\u001b[39;00m\n\u001b[0;32m     24\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mtensorboard\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mcompat\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mproto\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39msummary_pb2\u001b[39;00m \u001b[39mimport\u001b[39;00m \u001b[39m*\u001b[39m  \u001b[39m# noqa\u001b[39;00m\n\u001b[1;32m---> 25\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mdtypes\u001b[39;00m \u001b[39mimport\u001b[39;00m as_dtype  \u001b[39m# noqa\u001b[39;00m\n\u001b[0;32m     26\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mdtypes\u001b[39;00m \u001b[39mimport\u001b[39;00m DType  \u001b[39m# noqa\u001b[39;00m\n\u001b[0;32m     27\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39m.\u001b[39;00m\u001b[39mdtypes\u001b[39;00m \u001b[39mimport\u001b[39;00m string  \u001b[39m# noqa\u001b[39;00m\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:572\u001b[0m\n\u001b[0;32m    554\u001b[0m np_resource \u001b[39m=\u001b[39m np\u001b[39m.\u001b[39mdtype([(\u001b[39m\"\u001b[39m\u001b[39mresource\u001b[39m\u001b[39m\"\u001b[39m, np\u001b[39m.\u001b[39mubyte)])\n\u001b[0;32m    556\u001b[0m \u001b[39m# Standard mappings between types_pb2.DataType values and numpy.dtypes.\u001b[39;00m\n\u001b[0;32m    557\u001b[0m _NP_TO_TF \u001b[39m=\u001b[39m \u001b[39mfrozenset\u001b[39m(\n\u001b[0;32m    558\u001b[0m     [\n\u001b[0;32m    559\u001b[0m         (np\u001b[39m.\u001b[39mfloat16, float16),\n\u001b[0;32m    560\u001b[0m         (np\u001b[39m.\u001b[39mfloat32, float32),\n\u001b[0;32m    561\u001b[0m         (np\u001b[39m.\u001b[39mfloat64, float64),\n\u001b[0;32m    562\u001b[0m         (np\u001b[39m.\u001b[39mint32, int32),\n\u001b[0;32m    563\u001b[0m         (np\u001b[39m.\u001b[39mint64, int64),\n\u001b[0;32m    564\u001b[0m         (np\u001b[39m.\u001b[39muint8, uint8),\n\u001b[0;32m    565\u001b[0m         (np\u001b[39m.\u001b[39muint16, uint16),\n\u001b[0;32m    566\u001b[0m         (np\u001b[39m.\u001b[39muint32, uint32),\n\u001b[0;32m    567\u001b[0m         (np\u001b[39m.\u001b[39muint64, uint64),\n\u001b[0;32m    568\u001b[0m         (np\u001b[39m.\u001b[39mint16, int16),\n\u001b[0;32m    569\u001b[0m         (np\u001b[39m.\u001b[39mint8, int8),\n\u001b[0;32m    570\u001b[0m         (np\u001b[39m.\u001b[39mcomplex64, complex64),\n\u001b[0;32m    571\u001b[0m         (np\u001b[39m.\u001b[39mcomplex128, complex128),\n\u001b[1;32m--> 572\u001b[0m         (np\u001b[39m.\u001b[39;49mobject, string),\n\u001b[0;32m    573\u001b[0m         (np\u001b[39m.\u001b[39mbool, \u001b[39mbool\u001b[39m),\n\u001b[0;32m    574\u001b[0m         (_np_qint8, qint8),\n\u001b[0;32m    575\u001b[0m         (_np_quint8, quint8),\n\u001b[0;32m    576\u001b[0m         (_np_qint16, qint16),\n\u001b[0;32m    577\u001b[0m         (_np_quint16, quint16),\n\u001b[0;32m    578\u001b[0m         (_np_qint32, qint32),\n\u001b[0;32m    579\u001b[0m         \u001b[39m# TODO(#1677): _np_bfloat16 is defined as 0. This causes `as_dtype` to\u001b[39;00m\n\u001b[0;32m    580\u001b[0m         \u001b[39m# error. Add below back after we fix `TF_bfloat16_type`.\u001b[39;00m\n\u001b[0;32m    581\u001b[0m         \u001b[39m# (_np_bfloat16, bfloat16),\u001b[39;00m\n\u001b[0;32m    582\u001b[0m     ]\n\u001b[0;32m    583\u001b[0m )\n\u001b[0;32m    584\u001b[0m _TF_TO_NP \u001b[39m=\u001b[39m {\n\u001b[0;32m    585\u001b[0m     types_pb2\u001b[39m.\u001b[39mDT_HALF: np\u001b[39m.\u001b[39mfloat16,\n\u001b[0;32m    586\u001b[0m     types_pb2\u001b[39m.\u001b[39mDT_FLOAT: np\u001b[39m.\u001b[39mfloat32,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    629\u001b[0m     types_pb2\u001b[39m.\u001b[39mDT_BFLOAT16_REF: _np_bfloat16,\n\u001b[0;32m    630\u001b[0m }\n\u001b[0;32m    632\u001b[0m _QUANTIZED_DTYPES_NO_REF \u001b[39m=\u001b[39m \u001b[39mfrozenset\u001b[39m([qint8, quint8, qint16, quint16, qint32])\n\nFile \u001b[1;32mc:\\Python\\Python392\\lib\\site-packages\\numpy\\__init__.py:305\u001b[0m, in \u001b[0;36m__getattr__\u001b[1;34m(attr)\u001b[0m\n\u001b[0;32m    300\u001b[0m     warnings\u001b[39m.\u001b[39mwarn(\n\u001b[0;32m    301\u001b[0m         \u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mIn the future `np.\u001b[39m\u001b[39m{\u001b[39;00mattr\u001b[39m}\u001b[39;00m\u001b[39m` will be defined as the \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[0;32m    302\u001b[0m         \u001b[39m\"\u001b[39m\u001b[39mcorresponding NumPy scalar.\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mFutureWarning\u001b[39;00m, stacklevel\u001b[39m=\u001b[39m\u001b[39m2\u001b[39m)\n\u001b[0;32m    304\u001b[0m \u001b[39mif\u001b[39;00m attr \u001b[39min\u001b[39;00m __former_attrs__:\n\u001b[1;32m--> 305\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mAttributeError\u001b[39;00m(__former_attrs__[attr])\n\u001b[0;32m    307\u001b[0m \u001b[39m# Importing Tester requires importing all of UnitTest which is not a\u001b[39;00m\n\u001b[0;32m    308\u001b[0m \u001b[39m# cheap import Since it is mainly used in test suits, we lazy import it\u001b[39;00m\n\u001b[0;32m    309\u001b[0m \u001b[39m# here to save on the order of 10 ms of import time for most users\u001b[39;00m\n\u001b[0;32m    310\u001b[0m \u001b[39m#\u001b[39;00m\n\u001b[0;32m    311\u001b[0m \u001b[39m# The previous way Tester was imported also had a side effect of adding\u001b[39;00m\n\u001b[0;32m    312\u001b[0m \u001b[39m# the full `numpy.testing` namespace\u001b[39;00m\n\u001b[0;32m    313\u001b[0m \u001b[39mif\u001b[39;00m attr \u001b[39m==\u001b[39m \u001b[39m'\u001b[39m\u001b[39mtesting\u001b[39m\u001b[39m'\u001b[39m:\n\n\u001b[1;31mAttributeError\u001b[0m: module 'numpy' has no attribute 'object'.\n`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. \nThe aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations"
}

**Comment by effusiveperiscope** [comment]
What version of numpy are you using? The version listed in requirements.txt is 1.23.5.

**Comment by cody151** [comment]
> What version of numpy are you using? The version listed in requirements.txt is 1.23.5.

My installation is currently on v1.24.2, it should still run correct?

**Comment by mya2152** [comment]
> What version of numpy are you using? The version listed in requirements.txt is 1.23.5.

My installation is currently on v1.24.2, it should still run correct?

**Comment by effusiveperiscope** [comment]
The np.object alias seems to have been deprecated in 1.24.0. I'm not sure tensorboard has been updated to reflect this. You may want to downgrade.

**Comment by mya2152** [comment]
> The np.object alias seems to have been deprecated in 1.24.0. I'm not sure tensorboard has been updated to reflect this. You may want to downgrade.

Solved, thanks again!
