### ISSUE TITLE
ERROR: Could not build wheels for fairseq, pyworld, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ExpnandBanana** [effusiveperiscope/so-vits-svc#18]
[errorlog.txt](https://github.com/effusiveperiscope/so-vits-svc/files/11132221/errorlog.txt)

**Solutions tried that didn't work** 
- Installing Windows SDK
- Installing Visual Studio Build Tools 
- Installing C++ Build Tools 
- Installing Python 3.9
- Installing Python 3.10
- Swapping from VSC/BuildTools 2022 to VSC/BuildTools 2019 
- Clean wipe/reinstall of everything

**Comment by cody151** [comment]
These are issues with your Python environment. Consult Python documentation for issues not related to this project.
