### ISSUE TITLE
CPU training is not allowed

### ISSUE THREAD

**Issue by cody151** [effusiveperiscope/so-vits-svc#22]
Hello when trying to run the train.py file I keep getting assertion error: CPU training is not allowed

Platform Win10 64
CUDA 12.1 installed 
VSCode latest, all dependencies installed, ipynb jupyter notebook being used, inference notebook works fine in generating but as soon as I try to train this happens

**Comment by cody151** [comment]
assert torch.cuda.is_available(), "CPU training is not allowed."
AssertionError: CPU training is not allowed.

**Comment by effusiveperiscope** [comment]
Have you installed the correct version of pytorch for your CUDA?

**Comment by cody151** [comment]
> Have you installed the correct version of pytorch for your CUDA?

Yes, I fixed it but now it's saying I don't have enough VRAm I need to run it on CPU instead

**Comment by effusiveperiscope** [comment]
See https://github.com/effusiveperiscope/so-vits-svc/issues/23#issuecomment-1500764594 and remove the assert; frankly I'm not sure if training is possible on CPU or how fast it will be.
