### ISSUE TITLE
No such file or directory: './dataset/44k'

### ISSUE THREAD

**Issue by JUSTMonika15** [effusiveperiscope/so-vits-svc#33]
Traceback (most recent call last):
  File "/content/so-vits-svc/preprocess_flist_config.py", line 38, in <module>
    for speaker in tqdm(os.listdir(args.source_dir)):
FileNotFoundError: [Errno 2] No such file or directory: './dataset/44k'

I am currently facing a problem that seems to be caused by a missing directory during the cloning process. In fact, I have noticed that the dataset directory is absent from this particular project.

**Comment by effusiveperiscope** [comment]
For training this directory should be created when running resample.py.

**Comment by byhhhh1** [comment]
Have you solved it yet? I had the same problem.

**Comment by Tamako0401** [comment]
Now I've solved the problem. There is a problem in the path of "Load the dataset from.zip in Google Drive for preprocessing". You need to manually add a folder with the same name as {ZIP_NAME}.zip to /content/so-vits-svc/dataset_raw

**Comment by sirai599** [comment]
> Now I've solved the problem. There is a problem in the path of "Load the dataset from.zip in Google Drive for preprocessing". You need to manually add a folder with the same name as {ZIP_NAME}.zip to /content/so-vits-svc/dataset_raw

How to do this? Plz help me
