### ISSUE TITLE
Error when trying to run inference_gui2/main.py

### ISSUE THREAD

**Issue by INFZEL** [effusiveperiscope/so-vits-svc#9]
![image](https://user-images.githubusercontent.com/82004608/226492605-3d3e4eb4-8197-41b6-a081-5a4d3196090d.png)
Here's what shows up. 
I'm on windows 11 and I don't know anything about coding, I'm just a casual user. Any fix for this problem?

**Comment by effusiveperiscope** [comment]
Are you trying to run the CLI or the GUI? inference_main.py is old code used for inferring from the command line. If you need to run the GUI, run `python inference_gui2.py`.

**Comment by INFZEL** [comment]
i fixed it by downloading every single requirement i could find online.
